from __future__ import annotations

import csv
import io
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel, EmailStr
from supabase import Client

from app.core.config import get_settings
from app.core.security import get_current_firm_user
from app.db import get_db
from app.db import repo
from app.db.urls import portal_link
from app.models.enums import (
    ClientStatus,
    Country,
    EntityType,
    MessageChannel,
    MessageDeliveryStatus,
)
from app.models.staff import FirmUser
from app.services import checklist_generator
from app.services.completion import recompute_client_completion
from app.services.messaging import send_message
from app.services.signature_service import send_engagement_letter

router = APIRouter()


def _build_cpaos_client_report_pdf(firm: dict, clients: list[dict]) -> bytes:
    from fpdf import FPDF

    STATUS_COLORS: dict[str, tuple[int, int, int]] = {
        "completed": (16, 185, 129),
        "in_progress": (245, 158, 11),
        "invited": (148, 163, 184),
        "under_review": (37, 99, 235),
        "signature_pending": (168, 85, 247),
        "documents_pending": (245, 158, 11),
        "active": (100, 116, 139),
    }

    def _safe(s: str) -> str:
        return s.encode("ascii", "replace").decode("ascii")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 12, "CPAOS", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, _safe(firm["name"]), new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"Client Onboarding Report - Generated {datetime.utcnow().strftime('%d %B %Y %H:%M')}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    pdf.set_draw_color(226, 232, 240)
    y = pdf.get_y()
    pdf.line(10, y, 200, y)
    pdf.ln(6)

    n = len(clients)
    completed = sum(1 for c in clients if c.get("status") == ClientStatus.completed.value)
    avg_pct = int(round(sum(int(c.get("completion_pct", 0)) for c in clients) / n)) if n else 0

    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 41, 59)
    summary = f"Total clients: {n}    Completed: {completed}    Avg completion: {avg_pct}%"
    pdf.cell(0, 10, _safe(summary), fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(37, 99, 235)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(55, 8, "Client", fill=True)
    pdf.cell(25, 8, "Country", fill=True)
    pdf.cell(35, 8, "Entity", fill=True)
    pdf.cell(25, 8, "Status", fill=True)
    pdf.cell(25, 8, "Complete %", align="R", fill=True)
    pdf.cell(25, 8, "Created", fill=True, new_x="LMARGIN", new_y="NEXT")

    for i, client in enumerate(clients):
        zebra = i % 2 == 0
        pdf.set_fill_color(248, 250, 252) if zebra else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(30, 41, 59)
        pdf.set_font("Helvetica", "", 8)

        name = _safe((client.get("client_name") or "")[:28])
        country = _safe(str(client.get("country", ""))[:22])
        et = str(client.get("entity_type", "")).replace("_", " ").title()[:18]
        entity = _safe(et)
        status_key = str(client.get("status", ""))
        status_label = _safe(status_key.replace("_", " ").title()[:16])
        created_raw = client.get("created_at")
        created = ""
        if created_raw:
            created = str(created_raw)[:10]

        pdf.cell(55, 7, name, fill=zebra)
        pdf.cell(25, 7, country, fill=zebra)
        pdf.cell(35, 7, entity, fill=zebra)

        r, g, b = STATUS_COLORS.get(status_key, (100, 116, 139))
        pdf.set_text_color(r, g, b)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(25, 7, status_label, fill=zebra)

        pdf.set_text_color(30, 41, 59)
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(25, 7, f"{client.get('completion_pct', 0)}%", align="R", fill=zebra)
        pdf.cell(25, 7, _safe(created), fill=zebra, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_draw_color(226, 232, 240)
    y2 = pdf.get_y()
    pdf.line(10, y2, 200, y2)
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 6, "Generated by CPAOS - Confidential - For internal use only", align="C", new_x="LMARGIN", new_y="NEXT")

    out = pdf.output(dest="S")
    if isinstance(out, str):
        return out.encode("latin-1")
    return bytes(out)


class CreateClientBody(BaseModel):
    client_name: str
    business_name: str | None = None
    email: EmailStr
    phone: str
    country: str
    entity_type: str
    services: list[str] = []
    industry: str | None = None
    financial_year_end: str | None = None
    assigned_to: uuid.UUID | None = None
    send_engagement_letter: bool = False


class PatchClientBody(BaseModel):
    status: str | None = None
    assigned_to: uuid.UUID | None = None


def _ensure_entity(country: str, raw: str) -> EntityType:
    try:
        return EntityType(raw)
    except ValueError as e:
        raise HTTPException(status_code=400, detail="Invalid entity_type") from e


def _ensure_country(raw: str) -> Country:
    try:
        return Country(raw)
    except ValueError as e:
        raise HTTPException(status_code=400, detail="Invalid country") from e


@router.post("/clients")
def create_client(
    body: CreateClientBody,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    firm = repo.firm_by_id(sb, current.firm_id)
    if not firm:
        raise HTTPException(status_code=404, detail="Firm not found")
    country = _ensure_country(body.country)
    entity = _ensure_entity(body.country, body.entity_type)
    tok = uuid.uuid4()
    link = portal_link(get_settings().frontend_url, firm["slug"], tok)
    assigned = str(body.assigned_to) if body.assigned_to else None
    ins = (
        sb.table("clients")
        .insert(
            {
                "firm_id": str(current.firm_id),
                "client_name": body.client_name,
                "business_name": body.business_name,
                "email": str(body.email).lower(),
                "phone": body.phone,
                "country": country.value,
                "entity_type": entity.value,
                "services": body.services,
                "industry": body.industry,
                "financial_year_end": body.financial_year_end,
                "assigned_to": assigned,
                "onboarding_link": link,
                "onboarding_token": str(tok),
                "status": ClientStatus.invited.value,
            }
        )
        .execute()
    )
    if not ins.data:
        raise HTTPException(status_code=500, detail="Failed to create client")
    client = ins.data[0]
    cid = uuid.UUID(str(client["id"]))

    specs = checklist_generator.generate_checklist(country.value, entity.value, body.services)
    rows = [
        {
            "client_id": str(cid),
            "category": spec["category"],
            "item_name": spec["item_name"],
            "description": spec["description"],
            "is_required": spec["is_required"],
            "display_order": spec["display_order"],
        }
        for spec in specs
    ]
    if rows:
        sb.table("checklist_items").insert(rows).execute()
    recompute_client_completion(sb, cid)
    repo.insert_activity(
        sb,
        client_id=cid,
        firm_id=current.firm_id,
        action="client_created",
        description="Client record created",
        performed_by=str(current.id),
    )
    client = repo.client_by_id(sb, cid, current.firm_id) or client

    doc_count = len(specs)
    deadline = "TBD"
    variables = {
        "client_name": client["client_name"],
        "firm_name": firm["name"],
        "portal_link": client["onboarding_link"],
        "doc_count": str(doc_count),
        "deadline": deadline,
        "completion_pct": str(client.get("completion_pct", 0)),
        "pending_items": "See portal",
    }

    if body.send_engagement_letter:
        send_engagement_letter(client, firm, sb)
        client = repo.client_by_id(sb, cid, current.firm_id) or client
    else:
        send_message(client["phone"], "welcome", variables)
        repo.insert_whatsapp_log(
            sb,
            client_id=cid,
            firm_id=current.firm_id,
            channel=MessageChannel.whatsapp.value,
            message_type="welcome",
            phone_number=client["phone"],
            message_content="welcome",
            status=MessageDeliveryStatus.sent.value,
        )
        repo.insert_activity(
            sb,
            client_id=cid,
            firm_id=current.firm_id,
            action="portal_sent",
            description="Welcome message sent",
            performed_by="system",
        )
        client = repo.client_by_id(sb, cid, current.firm_id) or client

    return {
        "id": str(client["id"]),
        "client_name": client["client_name"],
        "status": client["status"],
        "completion_pct": client.get("completion_pct", 0),
        "portal_link": client["onboarding_link"],
        "onboarding_token": str(client["onboarding_token"]),
    }


@router.get("/clients")
def list_clients(
    status: str | None = None,
    country: str | None = None,
    search: str | None = None,
    assigned_to: uuid.UUID | None = None,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    rows = repo.list_clients_filtered(
        sb,
        current.firm_id,
        status=status,
        country=country,
        search=search,
        assigned_to=assigned_to,
    )
    firm = repo.firm_by_id(sb, current.firm_id)
    if not firm:
        raise HTTPException(status_code=404, detail="Firm not found")
    return [
        {
            "id": str(c["id"]),
            "client_name": c["client_name"],
            "business_name": c.get("business_name"),
            "country": c["country"],
            "entity_type": c["entity_type"],
            "status": c["status"],
            "completion_pct": c.get("completion_pct", 0),
            "portal_link": portal_link(get_settings().frontend_url, firm["slug"], c["onboarding_token"]),
            "assigned_to": str(c["assigned_to"]) if c.get("assigned_to") else None,
            "created_at": c.get("created_at"),
        }
        for c in rows
    ]


@router.get("/clients/{client_id}")
def get_client(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    firm = repo.firm_by_id(sb, current.firm_id)
    return {
        "id": str(c["id"]),
        "client_name": c["client_name"],
        "business_name": c.get("business_name"),
        "email": c["email"],
        "phone": c["phone"],
        "country": c["country"],
        "entity_type": c["entity_type"],
        "services": c.get("services") or [],
        "status": c["status"],
        "completion_pct": c.get("completion_pct", 0),
        "portal_link": portal_link(get_settings().frontend_url, firm["slug"], c["onboarding_token"]) if firm else "",
        "engagement_letter_sent": c.get("engagement_letter_sent", False),
        "engagement_letter_signed": c.get("engagement_letter_signed", False),
        "signature_envelope_id": c.get("signature_envelope_id"),
    }


@router.get("/clients/{client_id}/checklist")
def get_checklist(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    cid = uuid.UUID(str(c["id"]))
    items = repo.checklist_items_for_client(sb, cid)
    return [
        {
            "id": str(i["id"]),
            "category": i["category"],
            "item_name": i["item_name"],
            "description": i.get("description", ""),
            "is_required": i.get("is_required", True),
            "status": i["status"],
            "document_id": str(i["document_id"]) if i.get("document_id") else None,
            "display_order": i.get("display_order", 0),
        }
        for i in items
    ]


@router.patch("/clients/{client_id}")
def patch_client(
    client_id: uuid.UUID,
    body: PatchClientBody,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    patch: dict = {"last_activity_at": datetime.now(timezone.utc).isoformat()}
    if body.status is not None:
        patch["status"] = body.status
    if body.assigned_to is not None:
        patch["assigned_to"] = str(body.assigned_to)
    repo.update_client(sb, client_id, patch)
    return {"ok": True}


class ReminderBody(BaseModel):
    template: str = "reminder_day2"


@router.post("/clients/{client_id}/send-reminder")
def send_reminder(
    client_id: uuid.UUID,
    body: ReminderBody,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    firm = repo.firm_by_id(sb, current.firm_id)
    if not firm:
        raise HTTPException(status_code=404, detail="Not found")
    cid = uuid.UUID(str(c["id"]))
    pending = repo.checklist_pending_for_client(sb, cid)
    pending_items = "\n".join(f"- {p['item_name']}" for p in pending[:10]) or "- None"
    variables = {
        "client_name": c["client_name"],
        "firm_name": firm["name"],
        "portal_link": portal_link(get_settings().frontend_url, firm["slug"], c["onboarding_token"]),
        "doc_count": str(len(pending)),
        "deadline": "Soon",
        "completion_pct": str(c.get("completion_pct", 0)),
        "pending_items": pending_items,
    }
    result = send_message(c["phone"], body.template, variables)
    ch = MessageChannel.whatsapp.value
    if result.get("channel") == "sms":
        ch = MessageChannel.sms.value
    repo.insert_whatsapp_log(
        sb,
        client_id=cid,
        firm_id=current.firm_id,
        channel=ch,
        message_type=body.template,
        phone_number=c["phone"],
        message_content=body.template,
        status=MessageDeliveryStatus.sent.value if result.get("status") == "sent" else MessageDeliveryStatus.failed.value,
    )
    return result


@router.get("/clients/{client_id}/messages")
def client_messages(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    cid = uuid.UUID(str(c["id"]))
    logs = repo.whatsapp_logs_for_client(sb, cid)
    return [
        {
            "id": str(l["id"]),
            "channel": l["channel"],
            "message_type": l["message_type"],
            "phone_number": l["phone_number"],
            "message_content": l["message_content"],
            "status": l["status"],
            "sent_at": l.get("sent_at"),
        }
        for l in logs
    ]


@router.get("/clients/{client_id}/activity")
def client_activity(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    cid = uuid.UUID(str(c["id"]))
    r = (
        sb.table("onboarding_activity")
        .select("*")
        .eq("client_id", str(cid))
        .order("created_at", desc=True)
        .execute()
    )
    rows = r.data or []
    return [
        {
            "id": str(a["id"]),
            "action": a["action"],
            "description": a["description"],
            "performed_by": a["performed_by"],
            "created_at": a.get("created_at"),
        }
        for a in rows
    ]


@router.post("/clients/{client_id}/resend-engagement-letter")
def resend_engagement(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    c = repo.client_by_id(sb, client_id, current.firm_id)
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    firm = repo.firm_by_id(sb, current.firm_id)
    if not firm:
        raise HTTPException(status_code=404, detail="Not found")
    return send_engagement_letter(c, firm, sb)


class BulkRemindBody(BaseModel):
    client_ids: list[uuid.UUID]


@router.post("/clients/bulk-remind")
def bulk_remind(
    body: BulkRemindBody,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    firm = repo.firm_by_id(sb, current.firm_id)
    if not firm:
        raise HTTPException(status_code=404, detail="Not found")
    sent = 0
    failed = 0
    for cid in body.client_ids:
        c = repo.client_by_id(sb, cid, current.firm_id)
        if not c:
            failed += 1
            continue
        pending = repo.checklist_pending_for_client(sb, cid)
        pending_items = "\n".join(f"- {p['item_name']}" for p in pending[:10]) or "- None"
        variables = {
            "client_name": c["client_name"],
            "firm_name": firm["name"],
            "portal_link": portal_link(get_settings().frontend_url, firm["slug"], c["onboarding_token"]),
            "doc_count": str(len(pending)),
            "deadline": "Soon",
            "completion_pct": str(c.get("completion_pct", 0)),
            "pending_items": pending_items,
        }
        result = send_message(c["phone"], "reminder_day2", variables)
        ch = MessageChannel.whatsapp.value
        if result.get("channel") == "sms":
            ch = MessageChannel.sms.value
        repo.insert_whatsapp_log(
            sb,
            client_id=cid,
            firm_id=current.firm_id,
            channel=ch,
            message_type="bulk_reminder",
            phone_number=c["phone"],
            message_content="reminder_day2",
            status=MessageDeliveryStatus.sent.value if result.get("status") == "sent" else MessageDeliveryStatus.failed.value,
        )
        if result.get("status") == "sent":
            sent += 1
        else:
            failed += 1
    return {"sent": sent, "failed": failed}


@router.get("/clients/export-csv")
def export_clients_csv(
    ids: str | None = None,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    if ids:
        id_list = [uuid.UUID(x.strip()) for x in ids.split(",") if x.strip()]
        rows = repo.clients_in_ids(sb, current.firm_id, id_list) if id_list else []
    else:
        rows = repo.list_clients_filtered(sb, current.firm_id)
    assignees = {uuid.UUID(str(u["id"])): u["full_name"] for u in repo.firm_users_for_firm(sb, current.firm_id)}
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(
        ["Client Name", "Business", "Country", "Entity", "Status", "Completion %", "Assigned To", "Created At"]
    )
    for c in rows:
        aid = c.get("assigned_to")
        an = assignees.get(uuid.UUID(str(aid)), "") if aid else ""
        w.writerow(
            [
                c["client_name"],
                c.get("business_name") or "",
                c["country"],
                c["entity_type"],
                c["status"],
                c.get("completion_pct", 0),
                an,
                str(c.get("created_at") or ""),
            ]
        )
    buf.seek(0)
    filename = f"clients-{datetime.utcnow().strftime('%Y-%m-%d')}.csv"
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


class GenerateReportBody(BaseModel):
    client_ids: list[uuid.UUID]


@router.post("/clients/generate-report")
def generate_client_report(
    body: GenerateReportBody,
    current: FirmUser = Depends(get_current_firm_user),
    sb: Client = Depends(get_db),
):
    if not body.client_ids:
        raise HTTPException(status_code=400, detail="No client_ids provided")
    firm = repo.firm_by_id(sb, current.firm_id)
    if not firm:
        raise HTTPException(status_code=404, detail="Firm not found")
    rows = repo.clients_in_ids(sb, current.firm_id, body.client_ids)
    rows.sort(key=lambda x: str(x.get("created_at") or ""), reverse=True)
    if not rows:
        raise HTTPException(status_code=400, detail="No matching clients for this firm")
    pdf_bytes = _build_cpaos_client_report_pdf(firm, rows)
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="cpaos-report-{date_str}.pdf"'},
    )
