from __future__ import annotations

import csv
import io
import uuid
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel, EmailStr
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.core.security import get_current_firm_user
from app.db import get_db
from app.models.onboarding import (
    ChecklistItem,
    ChecklistItemStatus,
    Client,
    ClientStatus,
    Country,
    EntityType,
    Firm,
    FirmUser,
    MessageChannel,
    MessageDeliveryStatus,
    OnboardingActivity,
    WhatsAppLog,
)
from app.services import checklist_generator
from app.services.completion import recompute_client_completion
from app.services.messaging import send_message
from app.services.signature_service import send_engagement_letter

router = APIRouter()


def _build_cpaos_client_report_pdf(firm: Firm, clients: list[Client]) -> bytes:
    from fpdf import FPDF

    STATUS_COLORS: dict[str, tuple[int, int, int]] = {
        "completed": (16, 185, 129),
        "in_progress": (245, 158, 11),
        "invited": (148, 163, 184),
        "under_review": (37, 99, 235),
        "signature_pending": (168, 85, 247),
        "documents_pending": (245, 158, 11),
        "active": (100, 116, 139),
    }

    def _safe(s: str) -> str:
        return s.encode("ascii", "replace").decode("ascii")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 12, "CPAOS", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, _safe(firm.name), new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"Client Onboarding Report - Generated {datetime.utcnow().strftime('%d %B %Y %H:%M')}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    pdf.set_draw_color(226, 232, 240)
    y = pdf.get_y()
    pdf.line(10, y, 200, y)
    pdf.ln(6)

    n = len(clients)
    completed = sum(1 for c in clients if c.status == ClientStatus.completed)
    avg_pct = int(round(sum(c.completion_pct for c in clients) / n)) if n else 0

    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 41, 59)
    summary = f"Total clients: {n}    Completed: {completed}    Avg completion: {avg_pct}%"
    pdf.cell(0, 10, _safe(summary), fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(37, 99, 235)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(55, 8, "Client", fill=True)
    pdf.cell(25, 8, "Country", fill=True)
    pdf.cell(35, 8, "Entity", fill=True)
    pdf.cell(25, 8, "Status", fill=True)
    pdf.cell(25, 8, "Complete %", align="R", fill=True)
    pdf.cell(25, 8, "Created", fill=True, new_x="LMARGIN", new_y="NEXT")

    for i, client in enumerate(clients):
        zebra = i % 2 == 0
        pdf.set_fill_color(248, 250, 252) if zebra else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(30, 41, 59)
        pdf.set_font("Helvetica", "", 8)

        name = _safe((client.client_name or "")[:28])
        country = _safe(client.country.value[:22])
        entity = _safe(client.entity_type.value.replace("_", " ").title()[:18])
        status_key = client.status.value
        status_label = _safe(status_key.replace("_", " ").title()[:16])
        created = client.created_at.strftime("%Y-%m-%d") if client.created_at else ""

        pdf.cell(55, 7, name, fill=zebra)
        pdf.cell(25, 7, country, fill=zebra)
        pdf.cell(35, 7, entity, fill=zebra)

        r, g, b = STATUS_COLORS.get(status_key, (100, 116, 139))
        pdf.set_text_color(r, g, b)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(25, 7, status_label, fill=zebra)

        pdf.set_text_color(30, 41, 59)
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(25, 7, f"{client.completion_pct}%", align="R", fill=zebra)
        pdf.cell(25, 7, _safe(created), fill=zebra, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_draw_color(226, 232, 240)
    y2 = pdf.get_y()
    pdf.line(10, y2, 200, y2)
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 6, "Generated by CPAOS - Confidential - For internal use only", align="C", new_x="LMARGIN", new_y="NEXT")

    out = pdf.output(dest="S")
    if isinstance(out, str):
        return out.encode("latin-1")
    return bytes(out)


def _portal_url(firm: Firm, client: Client) -> str:
    base = get_settings().frontend_url.rstrip("/")
    return f"{base}/portal/{firm.slug}/{client.onboarding_token}"


class CreateClientBody(BaseModel):
    client_name: str
    business_name: str | None = None
    email: EmailStr
    phone: str
    country: str
    entity_type: str
    services: list[str] = []
    industry: str | None = None
    financial_year_end: str | None = None
    assigned_to: uuid.UUID | None = None
    send_engagement_letter: bool = False


class PatchClientBody(BaseModel):
    status: str | None = None
    assigned_to: uuid.UUID | None = None


def _ensure_entity(country: str, raw: str) -> EntityType:
    try:
        et = EntityType(raw)
    except ValueError as e:
        raise HTTPException(status_code=400, detail="Invalid entity_type") from e
    return et


def _ensure_country(raw: str) -> Country:
    try:
        return Country(raw)
    except ValueError as e:
        raise HTTPException(status_code=400, detail="Invalid country") from e


@router.post("/clients")
def create_client(
    body: CreateClientBody,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    country = _ensure_country(body.country)
    entity = _ensure_entity(body.country, body.entity_type)

    client = Client(
        firm_id=current.firm_id,
        client_name=body.client_name,
        business_name=body.business_name,
        email=str(body.email),
        phone=body.phone,
        country=country,
        entity_type=entity,
        services=body.services,
        industry=body.industry,
        financial_year_end=body.financial_year_end,
        assigned_to=body.assigned_to,
        onboarding_link="",
        status=ClientStatus.invited,
    )
    db.add(client)
    db.flush()
    client.onboarding_link = _portal_url(firm, client)

    specs = checklist_generator.generate_checklist(country.value, entity.value, body.services)
    for spec in specs:
        db.add(
            ChecklistItem(
                client_id=client.id,
                category=spec["category"],
                item_name=spec["item_name"],
                description=spec["description"],
                is_required=spec["is_required"],
                display_order=spec["display_order"],
            )
        )
    recompute_client_completion(db, client)
    db.add(
        OnboardingActivity(
            client_id=client.id,
            firm_id=current.firm_id,
            action="client_created",
            description="Client record created",
            performed_by=str(current.id),
        )
    )
    db.commit()
    db.refresh(client)

    doc_count = len(specs)
    deadline = "TBD"
    variables = {
        "client_name": client.client_name,
        "firm_name": firm.name,
        "portal_link": client.onboarding_link,
        "doc_count": str(doc_count),
        "deadline": deadline,
        "completion_pct": str(client.completion_pct),
        "pending_items": "See portal",
    }

    if body.send_engagement_letter:
        send_engagement_letter(client, firm, db)
        db.refresh(client)
    else:
        send_message(client.phone, "welcome", variables)
        log = WhatsAppLog(
            client_id=client.id,
            firm_id=current.firm_id,
            channel=MessageChannel.whatsapp,
            message_type="welcome",
            phone_number=client.phone,
            message_content="welcome",
            status=MessageDeliveryStatus.sent,
        )
        db.add(log)
        db.add(
            OnboardingActivity(
                client_id=client.id,
                firm_id=current.firm_id,
                action="portal_sent",
                description="Welcome message sent",
                performed_by="system",
            )
        )
        db.commit()
        db.refresh(client)

    return {
        "id": str(client.id),
        "client_name": client.client_name,
        "status": client.status.value,
        "completion_pct": client.completion_pct,
        "portal_link": client.onboarding_link,
        "onboarding_token": str(client.onboarding_token),
    }


@router.get("/clients")
def list_clients(
    status: str | None = None,
    country: str | None = None,
    search: str | None = None,
    assigned_to: uuid.UUID | None = None,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    q = db.query(Client).filter(Client.firm_id == current.firm_id)
    if status:
        q = q.filter(Client.status == ClientStatus(status))
    if country:
        q = q.filter(Client.country == Country(country))
    if search:
        like = f"%{search}%"
        q = q.filter(Client.client_name.ilike(like))
    if assigned_to:
        q = q.filter(Client.assigned_to == assigned_to)
    rows = q.order_by(Client.created_at.desc()).all()
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    return [
        {
            "id": str(c.id),
            "client_name": c.client_name,
            "business_name": c.business_name,
            "country": c.country.value,
            "entity_type": c.entity_type.value,
            "status": c.status.value,
            "completion_pct": c.completion_pct,
            "portal_link": _portal_url(firm, c),
            "assigned_to": str(c.assigned_to) if c.assigned_to else None,
            "created_at": c.created_at.isoformat() if c.created_at else None,
        }
        for c in rows
    ]


@router.get("/clients/{client_id}")
def get_client(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    return {
        "id": str(c.id),
        "client_name": c.client_name,
        "business_name": c.business_name,
        "email": c.email,
        "phone": c.phone,
        "country": c.country.value,
        "entity_type": c.entity_type.value,
        "services": c.services,
        "status": c.status.value,
        "completion_pct": c.completion_pct,
        "portal_link": _portal_url(firm, c),
        "engagement_letter_sent": c.engagement_letter_sent,
        "engagement_letter_signed": c.engagement_letter_signed,
        "signature_envelope_id": c.signature_envelope_id,
    }


@router.get("/clients/{client_id}/checklist")
def get_checklist(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    items = db.query(ChecklistItem).filter(ChecklistItem.client_id == c.id).order_by(ChecklistItem.display_order).all()
    return [
        {
            "id": str(i.id),
            "category": i.category,
            "item_name": i.item_name,
            "description": i.description,
            "is_required": i.is_required,
            "status": i.status.value,
            "document_id": str(i.document_id) if i.document_id else None,
            "display_order": i.display_order,
        }
        for i in items
    ]


@router.patch("/clients/{client_id}")
def patch_client(
    client_id: uuid.UUID,
    body: PatchClientBody,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    if body.status is not None:
        c.status = ClientStatus(body.status)
    if body.assigned_to is not None:
        c.assigned_to = body.assigned_to
    c.last_activity_at = datetime.utcnow()
    db.add(c)
    db.commit()
    return {"ok": True}


class ReminderBody(BaseModel):
    template: str = "reminder_day2"


@router.post("/clients/{client_id}/send-reminder")
def send_reminder(
    client_id: uuid.UUID,
    body: ReminderBody,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    pending = (
        db.query(ChecklistItem)
        .filter(ChecklistItem.client_id == c.id, ChecklistItem.status == ChecklistItemStatus.pending)
        .all()
    )
    pending_items = "\n".join(f"- {p.item_name}" for p in pending[:10]) or "- None"
    variables = {
        "client_name": c.client_name,
        "firm_name": firm.name,
        "portal_link": _portal_url(firm, c),
        "doc_count": str(len(pending)),
        "deadline": "Soon",
        "completion_pct": str(c.completion_pct),
        "pending_items": pending_items,
    }
    result = send_message(c.phone, body.template, variables)
    ch = MessageChannel.whatsapp
    if result.get("channel") == "sms":
        ch = MessageChannel.sms
    log = WhatsAppLog(
        client_id=c.id,
        firm_id=current.firm_id,
        channel=ch,
        message_type=body.template,
        phone_number=c.phone,
        message_content=body.template,
        status=MessageDeliveryStatus.sent if result.get("status") == "sent" else MessageDeliveryStatus.failed,
    )
    db.add(log)
    db.commit()
    return result


@router.get("/clients/{client_id}/messages")
def client_messages(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    logs = (
        db.query(WhatsAppLog)
        .filter(WhatsAppLog.client_id == c.id)
        .order_by(WhatsAppLog.sent_at.desc())
        .all()
    )
    return [
        {
            "id": str(l.id),
            "channel": l.channel.value,
            "message_type": l.message_type,
            "phone_number": l.phone_number,
            "message_content": l.message_content,
            "status": l.status.value,
            "sent_at": l.sent_at.isoformat(),
        }
        for l in logs
    ]


@router.get("/clients/{client_id}/activity")
def client_activity(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    rows = (
        db.query(OnboardingActivity)
        .filter(OnboardingActivity.client_id == c.id)
        .order_by(OnboardingActivity.created_at.desc())
        .all()
    )
    return [
        {
            "id": str(a.id),
            "action": a.action,
            "description": a.description,
            "performed_by": a.performed_by,
            "created_at": a.created_at.isoformat(),
        }
        for a in rows
    ]


@router.post("/clients/{client_id}/resend-engagement-letter")
def resend_engagement(
    client_id: uuid.UUID,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    c = db.query(Client).filter(Client.id == client_id, Client.firm_id == current.firm_id).first()
    if not c:
        raise HTTPException(status_code=404, detail="Not found")
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    return send_engagement_letter(c, firm, db)


class BulkRemindBody(BaseModel):
    client_ids: list[uuid.UUID]


@router.post("/clients/bulk-remind")
def bulk_remind(
    body: BulkRemindBody,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    sent = 0
    failed = 0
    for cid in body.client_ids:
        c = db.query(Client).filter(Client.id == cid, Client.firm_id == current.firm_id).first()
        if not c:
            failed += 1
            continue
        pending = (
            db.query(ChecklistItem)
            .filter(ChecklistItem.client_id == c.id, ChecklistItem.status == ChecklistItemStatus.pending)
            .all()
        )
        pending_items = "\n".join(f"- {p.item_name}" for p in pending[:10]) or "- None"
        variables = {
            "client_name": c.client_name,
            "firm_name": firm.name,
            "portal_link": _portal_url(firm, c),
            "doc_count": str(len(pending)),
            "deadline": "Soon",
            "completion_pct": str(c.completion_pct),
            "pending_items": pending_items,
        }
        result = send_message(c.phone, "reminder_day2", variables)
        ch = MessageChannel.whatsapp
        if result.get("channel") == "sms":
            ch = MessageChannel.sms
        log = WhatsAppLog(
            client_id=c.id,
            firm_id=current.firm_id,
            channel=ch,
            message_type="bulk_reminder",
            phone_number=c.phone,
            message_content="reminder_day2",
            status=MessageDeliveryStatus.sent if result.get("status") == "sent" else MessageDeliveryStatus.failed,
        )
        db.add(log)
        if result.get("status") == "sent":
            sent += 1
        else:
            failed += 1
    db.commit()
    return {"sent": sent, "failed": failed}


@router.get("/clients/export-csv")
def export_clients_csv(
    ids: str | None = None,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    q = db.query(Client).filter(Client.firm_id == current.firm_id)
    if ids:
        id_list = [uuid.UUID(x.strip()) for x in ids.split(",") if x.strip()]
        if id_list:
            q = q.filter(Client.id.in_(id_list))
    rows = q.order_by(Client.created_at.desc()).all()
    assignees = {u.id: u.full_name for u in db.query(FirmUser).filter(FirmUser.firm_id == current.firm_id).all()}
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(
        ["Client Name", "Business", "Country", "Entity", "Status", "Completion %", "Assigned To", "Created At"]
    )
    for c in rows:
        an = assignees.get(c.assigned_to, "") if c.assigned_to else ""
        w.writerow(
            [
                c.client_name,
                c.business_name or "",
                c.country.value,
                c.entity_type.value,
                c.status.value,
                c.completion_pct,
                an,
                c.created_at.isoformat() if c.created_at else "",
            ]
        )
    buf.seek(0)
    filename = f"clients-{datetime.utcnow().strftime('%Y-%m-%d')}.csv"
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


class GenerateReportBody(BaseModel):
    client_ids: list[uuid.UUID]


@router.post("/clients/generate-report")
def generate_client_report(
    body: GenerateReportBody,
    current: FirmUser = Depends(get_current_firm_user),
    db: Session = Depends(get_db),
):
    if not body.client_ids:
        raise HTTPException(status_code=400, detail="No client_ids provided")
    firm = db.query(Firm).filter(Firm.id == current.firm_id).first()
    if not firm:
        raise HTTPException(status_code=404, detail="Firm not found")
    rows = (
        db.query(Client)
        .filter(Client.firm_id == current.firm_id, Client.id.in_(body.client_ids))
        .order_by(Client.created_at.desc())
        .all()
    )
    if not rows:
        raise HTTPException(status_code=400, detail="No matching clients for this firm")
    pdf_bytes = _build_cpaos_client_report_pdf(firm, rows)
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="cpaos-report-{date_str}.pdf"'},
    )
